// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STTB.Backend.Data;

#nullable disable

namespace STTB.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311070525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STTB.Backend.Models.Berita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kategori_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Konten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tanggal_Publikasi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Thumbnail_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kategori_Id");

                    b.ToTable("Beritas");
                });

            modelBuilder.Entity("STTB.Backend.Models.Kategori_Berita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama_Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kategori_Beritas");
                });

            modelBuilder.Entity("STTB.Backend.Models.Berita", b =>
                {
                    b.HasOne("STTB.Backend.Models.Kategori_Berita", "Kategori_Berita")
                        .WithMany("Beritas")
                        .HasForeignKey("Kategori_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori_Berita");
                });

            modelBuilder.Entity("STTB.Backend.Models.Kategori_Berita", b =>
                {
                    b.Navigation("Beritas");
                });
#pragma warning restore 612, 618
        }
    }
}
