// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STTB.Backend.Data;

#nullable disable

namespace STTB.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STTB.Backend.Models.Berita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kategori_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Konten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tanggal_Publikasi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Thumbnail_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kategori_Id");

                    b.ToTable("Beritas");
                });

            modelBuilder.Entity("STTB.Backend.Models.Dokumen_Unduhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Link_File")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama_Dokumen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dokumen_Unduhans");
                });

            modelBuilder.Entity("STTB.Backend.Models.Dosen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bidang_Keahlian")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama_Lengkap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pendidikan_Terakhir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dosens");
                });

            modelBuilder.Entity("STTB.Backend.Models.Dosen_Prodi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dosen_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Prodi_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Dosen_Id");

                    b.HasIndex("Prodi_Id");

                    b.ToTable("Dosen_Prodis");
                });

            modelBuilder.Entity("STTB.Backend.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Jawaban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pertanyaan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("STTB.Backend.Models.Fasilitas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Foto_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama_Fasilitas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fasilitas");
                });

            modelBuilder.Entity("STTB.Backend.Models.Form_Pendaftaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Church_Affiliation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Program_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Statement_Of_Faith")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tanggal_Submit")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Program_Id");

                    b.ToTable("Form_Pendaftarans");
                });

            modelBuilder.Entity("STTB.Backend.Models.Kategori_Berita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama_Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kategori_Beritas");
                });

            modelBuilder.Entity("STTB.Backend.Models.Kategori_Kegiatan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama_Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kategori_Kegiatans");
                });

            modelBuilder.Entity("STTB.Backend.Models.Kegiatan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kategori_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama_Kegiatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tanggal_Mulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Tanggal_Selesai")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kategori_Id");

                    b.ToTable("Kegiatans");
                });

            modelBuilder.Entity("STTB.Backend.Models.Mata_Kuliah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail_Perincian")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kategori_Mk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama_Mk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prodi_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Prodi_Id");

                    b.ToTable("Mata_Kuliahs");
                });

            modelBuilder.Entity("STTB.Backend.Models.Program_Studi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ketua_Prodi_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nama_Prodi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tingkat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ketua_Prodi_Id");

                    b.ToTable("Program_Studis");
                });

            modelBuilder.Entity("STTB.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("STTB.Backend.Models.Berita", b =>
                {
                    b.HasOne("STTB.Backend.Models.Kategori_Berita", "Kategori_Berita")
                        .WithMany("Beritas")
                        .HasForeignKey("Kategori_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori_Berita");
                });

            modelBuilder.Entity("STTB.Backend.Models.Dosen_Prodi", b =>
                {
                    b.HasOne("STTB.Backend.Models.Dosen", "Dosen")
                        .WithMany("Dosen_Prodis")
                        .HasForeignKey("Dosen_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STTB.Backend.Models.Program_Studi", "Program_Studi")
                        .WithMany("Dosen_Prodis")
                        .HasForeignKey("Prodi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dosen");

                    b.Navigation("Program_Studi");
                });

            modelBuilder.Entity("STTB.Backend.Models.Form_Pendaftaran", b =>
                {
                    b.HasOne("STTB.Backend.Models.Program_Studi", "Program_Studi")
                        .WithMany("Form_Pendaftarans")
                        .HasForeignKey("Program_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program_Studi");
                });

            modelBuilder.Entity("STTB.Backend.Models.Kegiatan", b =>
                {
                    b.HasOne("STTB.Backend.Models.Kategori_Kegiatan", "Kategori_Kegiatan")
                        .WithMany("Kegiatans")
                        .HasForeignKey("Kategori_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori_Kegiatan");
                });

            modelBuilder.Entity("STTB.Backend.Models.Mata_Kuliah", b =>
                {
                    b.HasOne("STTB.Backend.Models.Program_Studi", "Program_Studi")
                        .WithMany("Mata_Kuliahs")
                        .HasForeignKey("Prodi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program_Studi");
                });

            modelBuilder.Entity("STTB.Backend.Models.Program_Studi", b =>
                {
                    b.HasOne("STTB.Backend.Models.Dosen", "Ketua_Prodi")
                        .WithMany()
                        .HasForeignKey("Ketua_Prodi_Id");

                    b.Navigation("Ketua_Prodi");
                });

            modelBuilder.Entity("STTB.Backend.Models.Dosen", b =>
                {
                    b.Navigation("Dosen_Prodis");
                });

            modelBuilder.Entity("STTB.Backend.Models.Kategori_Berita", b =>
                {
                    b.Navigation("Beritas");
                });

            modelBuilder.Entity("STTB.Backend.Models.Kategori_Kegiatan", b =>
                {
                    b.Navigation("Kegiatans");
                });

            modelBuilder.Entity("STTB.Backend.Models.Program_Studi", b =>
                {
                    b.Navigation("Dosen_Prodis");

                    b.Navigation("Form_Pendaftarans");

                    b.Navigation("Mata_Kuliahs");
                });
#pragma warning restore 612, 618
        }
    }
}
